import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AppDatas } from "@/constant/config";
import SessionWrapper from "@/provider/SessionWrapper";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  weight: ["100", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: AppDatas.title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${roboto.variable} antialiased`}>
          <Header />
          <main className=" max-w-[500px] mx-auto">{children}</main>
          <Footer />
          <Toaster position="top-center" reverseOrder={false} />
        </body>
      </html>
    </SessionWrapper>
  );
}
